---
name: Catalyst-Plugin-OrderedParams
version: 0.02
author:
  - 'Andy Grundman, C<andy@hybridized.org>'
abstract: Maintain order of submitted form parameters
license: perl
requires:
  Catalyst: 5.30
  Tie::IxHash: 0
provides:
  Catalyst::Plugin::OrderedParams:
    file: lib/Catalyst/Plugin/OrderedParams.pm
    version: 0.02
generated_by: Module::Build version 0.2611
